import { StyleSheet } from "react-native";

export const styles = StyleSheet.create({
  view: {
    flexDirection: "column",
    alignContent: "start",
    justifyContent: "start",
    width: "100%",
    textAlign: "left",
    elevation: 0,
    height: "100%",
    backgroundColor: "#FEFBEF",
  },
  header: {
    backgroundColor: "#FEFBEF",
    width: "100%",
    display: "flex",
    flexDirection: "row",
    justifyContent: "start",
    alignItems: "center",
    height: 100,
    paddingHorizontal: 20,
  },
  header_content: {
    flexDirection: "row",
    justifyContent: "center",
    alignItems: "center",
    paddingVertical: 10,
    maxWidth: "100%",
    backgroundColor: "#FEFBEF",
  },
  header_title: {
    fontSize: 32,
    fontWeight: "normal",
    fontFamily: "Fraunces-Regular",
    letterSpacing: 2,
    color: "#333333",
  },
  header_searchBox: {
    marginLeft: 20, // Adjust the spacing as needed
    flex: 1, // Take up all available space
    flexDirection: "column",
    alignItems: "center",
    justifyContent: "flex-start",
    height: "100%",
    width: "100%",
    position: "relative",
  },
  text: {
    fontFamily: "Fraunces-Regular",
    fontSize: 32,
    color: "#403F2B",
    letterSpacing: 2,
  },
  searchContainer: {
    borderColor: "#403f2b",
    borderWidth: 1,
    height: 40,
    backgroundColor: "transparent",
    width: "100%",
    position: "relative",
  },
  searchInput: {
    flex: 1,
    fontSize: 16,
    color: "#403f2b",
    minHeight: 0,
    fontFamily: "Fraunces-Regular",
  },
  searchResultsContainer: {
    position: "absolute",
    top: 40,
    left: 0,
    right: 0,
    zIndex: 1,
    backgroundColor: "#FEFBEF",
    elevation: 0,
    flex: 1,
    borderWidth: 1,
    borderTopWidth: 0,
    borderColor: "#403F2B",
    width: "100%",
    maxHeight: 200,
    overflow: "hidden",
  },
  searchResultFont: {
    fontFamily: "Fraunces-Regular",
  },
  searchResultItem: {
    flexDirection: "row",
    justifyContent: "flex-start",
    alignItems: "center",
    gap: 10,
    padding: 0,
    margin: 0,
    width: "100%",
  },
  productName: {
    fontFamily: "Fraunces-Regular",
    fontSize: 16,
    color: "#403F2B",
    flexShrink: 1,
  },
  image: {
    backgroundColor: "#f1ede6",
  },
});
